service:
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: "External"
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
replicaCount: 1
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
rbac:
  create: true
autoscaling:
  enabled: false
