apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: angga.sr57@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - http01:
          ingress:
            class: emissary
            serviceType: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: letsencrypt-acme-mapping
  namespace: emissary
spec:
  prefix: /.well-known/acme-challenge/
  rewrite: ""
  host: airbyte.cloudtest5.my.id
  service: letsencrypt-acme-service.airbyte.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: letsencrypt-acme-service
  namespace: airbyte
spec:
  ports:
    - port: 80
      targetPort: 8089
  selector:
    acme.cert-manager.io/http01-solver: "true"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airbyte-tls
  namespace: airbyte
spec:
  commonName: airbyte.cloudtest5.my.id
  dnsNames:
    - airbyte.cloudtest5.my.id
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: airbyte-tls-secret
